version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      - home

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: php81
    restart: unless-stopped
    volumes:
      - ./app:/www
    links:
      - mysql
    networks:
      - home

  mysql:
    image: mysql:8.0.31
    container_name: mysql8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_db
    volumes:
      - './docker/mysql:/var/lib/mysql'
    networks:
      - home

networks:
  home:
    driver: bridge

